# 开发环境配置
debug: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authority?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 10000