# 测试环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: 123456
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
      timeout: 10000